#!/usr/bin/env python3
"""Local GenEpiO RAG + Ministral-3-8B metadata normalizer.

Pipeline
--------
1. Parse/index GenEpiO (including imported ontology terms).
2. Ministral extracts normalized concepts from a complete metadata record.
3. Each concept is retrieved against the local GenEpiO index.
4. Ministral selects only from retrieved candidates and emits grounded JSON.

Ontology IDs are never generated by the LLM; they must occur in the retrieval results.
"""

import argparse
import json
import re
from pathlib import Path
from urllib.request import urlretrieve

import joblib
import numpy as np
import pandas as pd
from rdflib import Graph, RDF, RDFS, OWL, URIRef
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

OBO = "http://purl.obolibrary.org/obo/"
IAO_LABEL = URIRef(OBO + "IAO_0000111")
IAO_DEF = URIRef(OBO + "IAO_0000115")
IAO_ALT = URIRef(OBO + "IAO_0000118")
OBOINOWL = "http://www.geneontology.org/formats/oboInOwl#"
SYN_PROPS = [
    IAO_ALT,
    URIRef(OBOINOWL + "hasExactSynonym"),
    URIRef(OBOINOWL + "hasRelatedSynonym"),
    URIRef(OBOINOWL + "hasBroadSynonym"),
    URIRef(OBOINOWL + "hasNarrowSynonym"),
]

DEFAULT_URL = "https://raw.githubusercontent.com/GenEpiO/genepio/master/genepio-full.owl"
DEFAULT_MODEL = "mistralai/Ministral-3-8B-Instruct-2512"

# ---------- ontology parsing / retrieval ----------

def compact_id(uri: str) -> str:
    if uri.startswith(OBO):
        tail = uri[len(OBO):]
        if "_" in tail:
            p, n = tail.split("_", 1)
            return f"{p}:{n}"
    return uri


def literals(g, s, p):
    return [str(o).strip() for o in g.objects(s, p) if str(o).strip()]


def parse_owl(path: Path) -> pd.DataFrame:
    g = Graph()
    g.parse(str(path))
    rows = []
    classes = set(g.subjects(RDF.type, OWL.Class)) | set(g.subjects(RDFS.label, None))
    for s in classes:
        if not isinstance(s, URIRef):
            continue
        labels = literals(g, s, RDFS.label) or literals(g, s, IAO_LABEL)
        if not labels:
            continue
        label = labels[0]
        syns = []
        for p in SYN_PROPS:
            syns.extend(literals(g, s, p))
        syns = list(dict.fromkeys(x for x in syns if x != label))
        defs = literals(g, s, IAO_DEF)
        parents = [compact_id(str(o)) for o in g.objects(s, RDFS.subClassOf) if isinstance(o, URIRef)]
        rows.append({
            "id": compact_id(str(s)),
            "iri": str(s),
            "label": label,
            "synonyms": syns,
            "definition": defs[0] if defs else "",
            "parents": parents,
        })
    if not rows:
        raise RuntimeError(f"No labelled OWL classes found in {path}")
    return pd.DataFrame(rows).drop_duplicates("iri").reset_index(drop=True)


def build_text(row):
    # Labels/synonyms are deliberately repeated so they dominate long definitions.
    syn = " ; ".join(row["synonyms"] or [])
    return f"{row['label']} {row['label']} {syn} {syn} {row['definition']}"


def build_index(df: pd.DataFrame, out: Path):
    texts = [build_text(r) for _, r in df.iterrows()]
    word = TfidfVectorizer(lowercase=True, ngram_range=(1, 2), min_df=1, sublinear_tf=True)
    char = TfidfVectorizer(lowercase=True, analyzer="char_wb", ngram_range=(3, 5), min_df=1, sublinear_tf=True)
    wm = word.fit_transform(texts)
    cm = char.fit_transform(texts)
    joblib.dump({"terms": df, "word": word, "char": char, "wm": wm, "cm": cm}, out, compress=3)


def normalize(s):
    return re.sub(r"\s+", " ", str(s).strip().lower())


def retrieve(idx, value: str, field: str = "", k: int = 10):
    q_value = value
    q_context = f"{field.replace('_', ' ')} {value}" if field else value
    sw1 = linear_kernel(idx["word"].transform([q_value]), idx["wm"]).ravel()
    sc1 = linear_kernel(idx["char"].transform([q_value]), idx["cm"]).ravel()
    sw2 = linear_kernel(idx["word"].transform([q_context]), idx["wm"]).ravel()
    sc2 = linear_kernel(idx["char"].transform([q_context]), idx["cm"]).ravel()
    score = 0.45 * sw1 + 0.35 * sc1 + 0.12 * sw2 + 0.08 * sc2

    nv = normalize(value)
    for i, r in idx["terms"].iterrows():
        names = [r["label"]] + list(r["synonyms"] or [])
        if nv in {normalize(x) for x in names}:
            score[i] += 1.0

    order = np.argsort(-score)[:k]
    out = []
    for i in order:
        r = idx["terms"].iloc[i]
        out.append({
            "rank": len(out) + 1,
            "score": round(float(score[i]), 4),
            "id": r["id"],
            "label": r["label"],
            "synonyms": list(r["synonyms"] or []),
            "definition": r["definition"],
            "parents": list(r["parents"] or []),
            "iri": r["iri"],
        })
    return out


# ---------- local Ministral ----------

class MinistralLocal:
    def __init__(self, model_id: str = DEFAULT_MODEL, max_new_tokens: int | None = None,
                 temperature: float = 0.0):
        from vllm import LLM

        self.model_id = model_id
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        print(f"Loading {model_id} ...", flush=True)
        self.model = LLM(
            model=model_id, tokenizer_mode="mistral", config_format="mistral",
            load_format="mistral", max_model_len=8192,
            limit_mm_per_prompt={"image": 0}, gpu_memory_utilization=0.85,
            max_num_seqs=32, enable_prefix_caching=False,
        )

    def chat(self, system: str, user: str, schema: dict | None = None) -> str:
        output = self.chat_batch(system, [user], schemas=[schema])[0].outputs[0]
        if output.finish_reason == "length":
            raise ValueError("LLM response reached its token limit; refusing incomplete output")
        return output.text.strip()

    def chat_batch(self, system: str, users: list[str], schemas: list[dict | None] | None = None) -> list:
        """Batch only inference; extraction, retrieval and validation stay unchanged."""
        from vllm import SamplingParams
        from vllm.sampling_params import StructuredOutputsParams

        max_tokens = self.max_new_tokens or 768
        messages = [[{"role": "system", "content": system},
                     {"role": "user", "content": user}] for user in users]
        if schemas is None or len(schemas) != len(users) or any(s is None for s in schemas):
            raise ValueError("A JSON schema is required for every inference request")
        params = [SamplingParams(temperature=self.temperature, max_tokens=max_tokens,
                  structured_outputs=StructuredOutputsParams(json=s)) for s in schemas]
        return self.model.chat(messages, params, use_tqdm=False)


def extract_json(text: str):
    """Parse JSON, tolerating ```json fences and incidental prose."""
    t = text.strip()
    t = re.sub(r"^```(?:json)?\s*", "", t, flags=re.I)
    t = re.sub(r"\s*```$", "", t)
    try:
        return json.loads(t)
    except json.JSONDecodeError:
        # Prefer an object, then an array.
        for left, right in [("{", "}"), ("[", "]")]:
            a, b = t.find(left), t.rfind(right)
            if a >= 0 and b > a:
                try:
                    return json.loads(t[a:b+1])
                except json.JSONDecodeError:
                    pass
        raise ValueError(f"Model did not return parseable JSON:\n{text}")


EXTRACT_SYSTEM = """You normalize messy biological sample metadata.
Extract only concepts explicitly stated or very strongly implied by the supplied record.
Do not assign ontology IDs. Do not make unsupported clinical or epidemiological inferences.
A source field can contain multiple concepts.
Return JSON only, with this exact top-level shape:
{"c": [["source_field", "concept_type", "normalized_query"], ...]}
Use actual source field names. Do not repeat raw metadata, evidence, explanations or confidence.
Useful concept types include organism, specimen, anatomical_site, disease, clinical_context,
environment, food, geographic_location, collection_process, treatment, phenotype, and other.
For ambiguous text, use a conservative normalized_query.
Retain biologically meaningful study context as a separate study or clinical_context concept,
including recognized biological study abbreviations. Keep the complete context in its query:
an environmental transmission study is a study/process concept, not just an organism.
Interpret biomedical/veterinary study-program abbreviations when meaningful, retaining the
study context separately from organism and specimen concepts in the same record.
Ignore identifiers, accessions and dates unless they themselves express a biological concept."""


GROUND_SYSTEM = """You ground extracted biological metadata concepts to ontology candidates.
Candidates for each concept are numbered 0 through 4 in retrieval order.
Select only a supplied candidate index. Never emit ontology IDs.
A concept may be unresolved if no candidate adequately represents it.
Prefer the most semantically precise candidate supported by the original metadata.
Match the entire extracted concept. A taxon alone does not represent a study, transmission
process or other compound context: use null if no candidate represents that context.
For organism concepts, use the whole record including biological taxonomic identifiers
to distinguish genus from species and select the most specific supported taxon.
An exact taxonomic identifier can specify a species even if the extracted search query
uses its genus name. Use the original metadata to resolve this specificity.
Return JSON only with this exact top-level shape:
{"s": [candidate_index_or_null, ...]}
Return exactly one selection per concept in concept order. Use null for unresolved.
Do not return labels, reasons, scores, confidence or ontology IDs."""


def extraction_schema(record: dict) -> dict:
    return {"type": "object", "properties": {"c": {"type": "array", "items": {
        "type": "array", "prefixItems": [
            {"type": "string", "enum": list(record)},
            {"type": "string", "minLength": 1},
            {"type": "string", "minLength": 1}],
        "minItems": 3, "maxItems": 3}}}, "required": ["c"], "additionalProperties": False}


def grounding_schema(bundles: list) -> dict:
    if not bundles:
        return {"type": "object", "properties": {"s": {"type": "array", "maxItems": 0}},
                "required": ["s"], "additionalProperties": False}
    return {"type": "object", "properties": {"s": {"type": "array",
        "prefixItems": [{"enum": [None] + list(range(min(5, len(b['candidates']))))}
                        for b in bundles],
        "minItems": len(bundles), "maxItems": len(bundles)}},
        "required": ["s"], "additionalProperties": False}


def reconstruct_concepts(raw: str, record: dict) -> list[dict]:
    obj = json.loads(raw)
    if set(obj) != {"c"} or not isinstance(obj['c'], list):
        raise ValueError("Expected compact concepts list")
    concepts = []
    for entry in obj['c']:
        if not isinstance(entry, list) or len(entry) != 3 or not all(isinstance(v, str) for v in entry):
            raise ValueError("Expected three strings per concept")
        field, kind, query = entry
        if field not in record or not kind.strip() or not query.strip():
            raise ValueError("Invalid source field or empty concept")
        concepts.append({"concept_type": kind, "source_field": field,
                         "raw_value": record[field], "normalized_query": query,
                         "evidence": f"{field}={record[field]}"})
    return concepts


def record_to_text(record: dict) -> str:
    lines = []
    for k, v in record.items():
        if v is None:
            continue
        s = str(v).strip()
        if not s or s.upper() in {"NA", "N/A", "NONE", "NULL", "NAN"}:
            continue
        lines.append(f"{k}={s}")
    return "\n".join(lines)


def ministral_extract(llm: MinistralLocal, record: dict) -> tuple[list[dict], str]:
    raw = llm.chat(EXTRACT_SYSTEM, "Metadata record:\n" + record_to_text(record),
                   schema=extraction_schema(record))
    return reconstruct_concepts(raw, record), raw


def retrieve_for_concepts(idx, concepts, k=5):
    bundles = []
    for i, c in enumerate(concepts):
        query = str(c.get("normalized_query") or c.get("raw_value") or "").strip()
        field = str(c.get("source_field") or c.get("concept_type") or "")
        if not query:
            hits = []
        else:
            hits = retrieve(idx, query, field, k)
        bundles.append({"concept_index": i, "concept": c, "candidates": hits})
    return bundles


def grounding_prompt(record: dict, bundles: list) -> str:
    compact = []
    for bundle in bundles:
        candidates = []
        definition_added = False
        for index, hit in enumerate(bundle['candidates'][:5]):
            candidate = {"index": index, "label": hit['label'],
                         "synonyms": hit['synonyms'][:8], "score": hit['score']}
            definition = ' '.join(hit['definition'].split())
            if definition and not definition_added:
                candidate['definition'] = definition[:160]
                definition_added = True
            candidates.append(candidate)
        concept = bundle['concept']
        compact.append({"concept": concept, "candidates": candidates})
    return ("Original metadata:\n" + record_to_text(record) +
            "\n\nExtracted concepts and retrieved candidates:\n" +
            json.dumps(compact, separators=(',', ':'), ensure_ascii=False))


def reconstruct_annotations(raw: str, bundles: list) -> list[dict]:
    obj = json.loads(raw)
    if set(obj) != {'s'} or not isinstance(obj['s'], list) or len(obj['s']) != len(bundles):
        raise ValueError("Expected one compact selection per concept")
    annotations = []
    for bundle, selected in zip(bundles, obj['s']):
        candidates = bundle['candidates'][:5]
        annotation = {"concept_index": bundle['concept_index'], "status": "unresolved",
                      "ontology_id": None, "label": None,
                      "reason": "No supplied candidate selected", "retrieval_score": None}
        if selected is not None:
            # Defense in depth: schema constraints never replace Python validation.
            if type(selected) is not int or not 0 <= selected < len(candidates):
                annotation['reason'] = "LLM selected an invalid candidate index; rejected by validator"
            else:
                hit = candidates[selected]
                annotation.update(status="matched", ontology_id=hit['id'], label=hit['label'],
                                  retrieval_score=hit['score'],
                                  reason=f"Selected retrieved candidate {selected}")
        annotations.append(annotation)
    return annotations


def ministral_ground(llm: MinistralLocal, record: dict, bundles: list) -> tuple[list[dict], str]:
    if not bundles:
        return [], '{"s":[]}'
    raw = llm.chat(GROUND_SYSTEM, grounding_prompt(record, bundles),
                   schema=grounding_schema(bundles))
    return reconstruct_annotations(raw, bundles), raw


def annotate_record(idx, llm, record: dict, k=5, include_candidates=False):
    concepts, extraction_raw = ministral_extract(llm, record)
    bundles = retrieve_for_concepts(idx, concepts, k=k)
    annotations, grounding_raw = ministral_ground(llm, record, bundles)

    by_index = {a.get("concept_index"): a for a in annotations}
    out = []
    for b in bundles:
        c = dict(b["concept"])
        c["annotation"] = by_index.get(b["concept_index"], {
            "status": "unresolved", "ontology_id": None, "label": None,
            "reason": "No grounding response returned for this concept"
        })
        if include_candidates:
            c["candidates"] = b["candidates"]
        out.append(c)

    return {
        "metadata": record,
        "concepts": out,
        "model": llm.model_id,
        "debug": {
            "extraction_raw": extraction_raw,
            "grounding_raw": grounding_raw,
        },
    }


# ---------- CLI ----------

def parse_kv(items):
    record = {}
    for item in items or []:
        if "=" not in item:
            raise ValueError(f"Expected FIELD=VALUE, got: {item}")
        k, v = item.split("=", 1)
        record[k.strip()] = v.strip()
    return record


def cmd_download(args):
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    print(f"Downloading {args.url} -> {out}")
    urlretrieve(args.url, out)
    print(out)


def cmd_build(args):
    df = parse_owl(Path(args.owl))
    build_index(df, Path(args.index))
    print(f"Indexed {len(df):,} labelled classes -> {args.index}")


def cmd_query(args):
    idx = joblib.load(args.index)
    hits = retrieve(idx, args.value, args.field, args.k)
    print(json.dumps(hits, indent=2, ensure_ascii=False))


def cmd_annotate(args):
    idx = joblib.load(args.index)
    record = parse_kv(args.meta)
    if args.json_record:
        record.update(json.loads(Path(args.json_record).read_text()))
    if not record:
        raise ValueError("Provide at least one --meta FIELD=VALUE or --json-record file")

    llm = MinistralLocal(
        model_id=args.model,
        max_new_tokens=args.max_new_tokens,
        temperature=args.temperature,
    )
    result = annotate_record(idx, llm, record, k=args.k, include_candidates=args.include_candidates)
    # Debug contains raw model text and is useful initially but optional.
    if not args.debug:
        result.pop("debug", None)
    print(json.dumps(result, indent=2, ensure_ascii=False))


def cmd_annotate_tsv(args):
    idx = joblib.load(args.index)
    llm = MinistralLocal(
        model_id=args.model,
        max_new_tokens=args.max_new_tokens,
        temperature=args.temperature,
    )
    df = pd.read_csv(args.input, sep="\t", dtype=str).fillna("")
    if args.limit:
        df = df.head(args.limit)

    fields = args.fields or list(df.columns)
    missing = [x for x in fields if x not in df.columns]
    if missing:
        raise ValueError(f"Missing requested fields: {', '.join(missing)}")

    out = Path(args.output)
    with out.open("w", encoding="utf-8") as fh:
        for n, (_, row) in enumerate(df.iterrows(), 1):
            record = {f: row[f] for f in fields}
            result = annotate_record(idx, llm, record, k=args.k, include_candidates=args.include_candidates)
            if not args.debug:
                result.pop("debug", None)
            fh.write(json.dumps(result, ensure_ascii=False) + "\n")
            print(f"Annotated {n}/{len(df)}", flush=True)


def add_llm_args(p):
    p.add_argument("--model", default=DEFAULT_MODEL,
                   help="Hugging Face model ID or path to an already-downloaded local model directory")
    p.add_argument("--max-new-tokens", type=int, default=None,
                   help="Override the measurement ceiling (default: 768 for both passes)")
    p.add_argument("--temperature", type=float, default=0.0)
    p.add_argument("-k", type=int, default=5, help="Retrieved candidates per concept; grounding uses the first five")
    p.add_argument("--include-candidates", action="store_true")
    p.add_argument("--debug", action="store_true", help="Include raw model responses")


def main():
    ap = argparse.ArgumentParser(description="Local GenEpiO RAG with Ministral-3-8B concept extraction and grounding")
    sp = ap.add_subparsers(dest="cmd", required=True)

    p = sp.add_parser("download")
    p.add_argument("--url", default=DEFAULT_URL)
    p.add_argument("--output", default="genepio-full.owl")
    p.set_defaults(func=cmd_download)

    p = sp.add_parser("build")
    p.add_argument("--owl", default="genepio-full.owl")
    p.add_argument("--index", default="genepio_rag.joblib")
    p.set_defaults(func=cmd_build)

    p = sp.add_parser("query")
    p.add_argument("--index", default="genepio_rag.joblib")
    p.add_argument("--field", default="isolation_source")
    p.add_argument("--value", required=True)
    p.add_argument("-k", type=int, default=5)
    p.set_defaults(func=cmd_query)

    p = sp.add_parser("annotate")
    p.add_argument("--index", default="genepio_rag.joblib")
    p.add_argument("--meta", action="append", default=[], metavar="FIELD=VALUE")
    p.add_argument("--json-record", help="JSON object containing one metadata record")
    add_llm_args(p)
    p.set_defaults(func=cmd_annotate)

    p = sp.add_parser("annotate-tsv")
    p.add_argument("input")
    p.add_argument("--output", default="annotations.jsonl")
    p.add_argument("--index", default="genepio_rag.joblib")
    p.add_argument("--fields", nargs="*", help="Columns sent to the LLM; default: all")
    p.add_argument("--limit", type=int, help="Only process first N records")
    add_llm_args(p)
    p.set_defaults(func=cmd_annotate_tsv)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
